networks:
  work_net:

volumes:
  api_users_volume:

services:
  psql:
    image: postgres:latest
    container_name: psql_api
    ports:
      - "5433:5432"
    networks:
      - work_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: api_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
    - api_users_volume:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    container_name: api
    networks: 
      - work_net
    ports:
      - 8080:8080
    depends_on:
      psql:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:123@psql_api:5432/api_db?sslmode=disable